// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteFilesMessage': string;
  'fileList': string;
  'fileListItem': string;
  'filePathList': string;
  'fileSize': string;
  'noFiles': string;
  'pathContainer': string;
  'pathIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
