// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addCondition': string;
  'addConditionContent': string;
  'customFormats': string;
  'deleteButton': string;
  'footerActions': string;
}
export const cssExports: CssExports;
export default cssExports;
