// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'disabled': string;
  'option': string;
  'toggle': string;
  'toggleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
