// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'conversionDownloadComplete': string;
  'conversionProgress': string;
  'conversionProgressLabel': string;
  'conversionProgressOverlay': string;
  'convertToQuality': string;
  'customFormatScore': string;
  'progress': string;
  'protocol': string;
  'quality': string;
  'qualityLabel': string;
  'releaseTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
