// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'conversionPulseSpin': string;
  'convertingIcon': string;
  'status': string;
}
export const cssExports: CssExports;
export default cssExports;
