// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'annotatedEvidence': string;
  'blankpad': string;
  'conflictingDot': string;
  'conflictingText': string;
  'container': string;
  'decision': string;
  'decisionDetails': string;
  'decisionDetailsContent': string;
  'decisionHeader': string;
  'evidenceFields': string;
  'evidenceText': string;
  'fileAudit': string;
  'legend': string;
  'mode': string;
  'neutralDot': string;
  'neutralText': string;
  'noExplanation': string;
  'route': string;
  'sectionTitle': string;
  'signalLabel': string;
  'signalList': string;
  'signalRow': string;
  'signalValues': string;
  'summaryHeader': string;
  'summarySection': string;
  'supportingDot': string;
  'supportingText': string;
  'unmatchedText': string;
  'unrecordedFiles': string;
}
export const cssExports: CssExports;
export default cssExports;
