// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loadingOverlay': string;
  'photoCounter': string;
  'photoNavButton': string;
  'photoNavigation': string;
  'posterContainer': string;
  'posterImageWrapper': string;
  'sandersonOverlay': string;
  'sandersonOverlayImage': string;
  'spin': string;
}
export const cssExports: CssExports;
export default cssExports;
