// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'age': string;
  'cell': string;
  'customFormatScore': string;
  'download': string;
  'duration': string;
  'goldStar': string;
  'grabError': string;
  'graphicAudio': string;
  'indexer': string;
  'indexerFlags': string;
  'moreIndicator': string;
  'narrator': string;
  'narratorContent': string;
  'narratorName': string;
  'peers': string;
  'preferredBadge': string;
  'preferredRow': string;
  'protocol': string;
  'quality': string;
  'rank': string;
  'rejected': string;
  'size': string;
  'title': string;
  'titleContent': string;
  'titleLink': string;
  'titleMatch': string;
  'titleTextBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
