// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blankpad': string;
  'filterMenuContainer': string;
  'filteredMessage': string;
  'formatCount': string;
  'formatHeader': string;
  'formatSection': string;
  'formatTitle': string;
  'hiddenResultsHeader': string;
  'hiddenResultsPager': string;
  'hiddenResultsRange': string;
  'hiddenResultsTitle': string;
  'table': string;
}
export const cssExports: CssExports;
export default cssExports;
