// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteButton': string;
  'hardcoverConnectActions': string;
  'hardcoverIdentityAvatar': string;
  'hardcoverIdentityRow': string;
  'hardcoverIdentityText': string;
  'hardcoverInfo': string;
  'hardcoverMediaTypeToggle': string;
  'hardcoverSubsection': string;
  'hardcoverSubsectionTitle': string;
  'hideMetadataProfile': string;
  'labelIcon': string;
  'message': string;
}
export const cssExports: CssExports;
export default cssExports;
