// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkIcon': string;
  'confidence': string;
  'confidenceScore': string;
  'details': string;
  'folder': string;
  'folderName': string;
  'highConfidence': string;
  'lowConfidence': string;
  'matchReason': string;
  'mediumConfidence': string;
  'path': string;
  'row': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
