// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'folders': string;
  'info': string;
  'modalBody': string;
  'skipInfo': string;
}
export const cssExports: CssExports;
export default cssExports;
