// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'quickstartReturn': string;
  'quickstartReturnButtonContent': string;
}
export const cssExports: CssExports;
export default cssExports;
