// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controlsContainer': string;
  'leftControls': string;
  'rightControls': string;
  'rootFolderMessage': string;
  'syncAndToggle': string;
  'syncIndicator': string;
  'topRow': string;
}
export const cssExports: CssExports;
export default cssExports;
