// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'duration': string;
  'indexerFlags': string;
  'monitored': string;
  'narrator': string;
  'pageCount': string;
  'path': string;
  'position': string;
  'rating': string;
  'releaseDate': string;
  'status': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
