// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'toggleContainer': string;
  'toggleOption': string;
  'toggleSlider': string;
  'toggleSwitch': string;
}
export const cssExports: CssExports;
export default cssExports;
