// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alreadyExistsIcon': string;
  'content': string;
  'cover': string;
  'cover1': string;
  'cover2': string;
  'cover3': string;
  'icons': string;
  'loadingCovers': string;
  'loadingText': string;
  'mbLink': string;
  'mbLinkIcon': string;
  'overlay': string;
  'overview': string;
  'posterContainer': string;
  'pulse': string;
  'searchResult': string;
  'stackedCovers': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'underlay': string;
}
export const cssExports: CssExports;
export default cssExports;
