// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'addButtons': string;
  'bookAuthorName': string;
  'bookCountAndButton': string;
  'bookCover': string;
  'bookCoverImage': string;
  'bookInfo': string;
  'bookItem': string;
  'bookItemSelected': string;
  'bookMetadata': string;
  'bookOverview': string;
  'bookPosition': string;
  'bookRating': string;
  'bookReleaseDate': string;
  'bookSelect': string;
  'bookTitle': string;
  'booksList': string;
  'booksSection': string;
  'booksSectionTitle': string;
  'cancelButton': string;
  'container': string;
  'description': string;
  'info': string;
  'metadataSeparator': string;
  'monitorAllBooksToggle': string;
  'noBooksMessage': string;
  'notice': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
