// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'helpText': string;
  'inputStack': string;
  'intro': string;
  'saveError': string;
}
export const cssExports: CssExports;
export default cssExports;
