// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addRootFolderCard': string;
  'addRootFolderContent': string;
  'rootFolderBadges': string;
  'rootFolderCard': string;
  'rootFolderColumn': string;
  'rootFolderContent': string;
  'rootFolderDefault': string;
  'rootFolderDetails': string;
  'rootFolderName': string;
  'rootFolderPath': string;
  'rootFolderScope': string;
  'rootFoldersContainer': string;
  'rootFoldersStack': string;
}
export const cssExports: CssExports;
export default cssExports;
