// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addProfileCard': string;
  'addProfileContent': string;
  'addProfileText': string;
  'cloneButton': string;
  'columnHeader': string;
  'ignoredTerms': string;
  'ignoredTermsLabel': string;
  'ignoredTermsList': string;
  'metadataItem': string;
  'metadataLabel': string;
  'metadataValue': string;
  'profileCard': string;
  'profileColumn': string;
  'profileContent': string;
  'profileDetails': string;
  'profileHeader': string;
  'profileName': string;
  'profilesContainer': string;
  'profilesGrid': string;
  'profilesTwoColumn': string;
  'qualityAddProfileCard': string;
  'qualityProfileCard': string;
  'qualityProfileDetails': string;
}
export const cssExports: CssExports;
export default cssExports;
