// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addIndexer': string;
  'center': string;
  'indexers': string;
  'section': string;
  'sectionTitle': string;
  'sectionTitleFirst': string;
}
export const cssExports: CssExports;
export default cssExports;
