// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'message': string;
  'pendingImportStatus': string;
  'processing': string;
  'progress': string;
  'success': string;
}
export const cssExports: CssExports;
export default cssExports;
