// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonContainer': string;
  'buttonIcon': string;
  'buttonsContainer': string;
  'footer': string;
  'importMode': string;
  'largeFolderWarning': string;
  'largeFolderWarningIcon': string;
  'leftButtons': string;
  'matchingControl': string;
  'recentFoldersContainer': string;
  'rightButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
