// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'bulkSelect': string;
  'errorMessage': string;
  'filterContainer': string;
  'filterMenus': string;
  'filterText': string;
  'footer': string;
  'importMode': string;
  'leftButtons': string;
  'loadingContainer': string;
  'loadingText': string;
  'matchSummary': string;
  'matchingControl': string;
  'rightButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
