// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'faqLink': string;
  'loading': string;
  'mappedDrivesWarning': string;
  'modalBody': string;
  'nameColumn': string;
  'pathInput': string;
  'scroller': string;
}
export const cssExports: CssExports;
export default cssExports;
