// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'canvas': string;
  'content': string;
  'dragOverlay': string;
  'error': string;
  'gray': string;
  'green': string;
  'header': string;
  'loading': string;
  'orange': string;
  'palette': string;
  'pathBuilder': string;
  'purple': string;
  'visualBuilder': string;
}
export const cssExports: CssExports;
export default cssExports;
