// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'canvas': string;
  'canvasContent': string;
  'canvasFooter': string;
  'canvasHeader': string;
  'canvasOver': string;
  'chip': string;
  'chipContent': string;
  'colorLegend': string;
  'deleteButton': string;
  'dragging': string;
  'dropZone': string;
  'dropZoneActive': string;
  'dropZoneVisible': string;
  'emptyState': string;
  'gray': string;
  'green': string;
  'groupContent': string;
  'instructions': string;
  'legendItem': string;
  'orange': string;
  'pathBuilder': string;
  'purple': string;
}
export const cssExports: CssExports;
export default cssExports;
