// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'extension': string;
  'highlighted': string;
  'loader': string;
  'preview': string;
  'previewHeader': string;
  'previewPath': string;
  'segment': string;
  'segments': string;
}
export const cssExports: CssExports;
export default cssExports;
