// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'category': string;
  'categoryHeader': string;
  'gray': string;
  'green': string;
  'orange': string;
  'palette': string;
  'purple': string;
  'token': string;
  'tokens': string;
}
export const cssExports: CssExports;
export default cssExports;
