// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tool': string;
  'toolGroup': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export default cssExports;
