// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorCount': string;
  'errorGroup': string;
  'errorHeader': string;
  'errorItem': string;
  'errorList': string;
  'errorPath': string;
  'errorType': string;
  'loadingText': string;
  'panel': string;
  'success': string;
}
export const cssExports: CssExports;
export default cssExports;
