// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'location': string;
  'space': string;
}
export const cssExports: CssExports;
export default cssExports;
