// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'full': string;
  'half': string;
  'rating': string;
  'sizeLarge': string;
  'sizeMedium': string;
  'sizeSmall': string;
  'star': string;
  'starRating': string;
  'stars': string;
  'voteCount': string;
}
export const cssExports: CssExports;
export default cssExports;
