// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'calendarInnerPageBody': string;
  'calendarPageBody': string;
  'emptyState': string;
  'emptyStateMessage': string;
  'errorMessage': string;
}
export const cssExports: CssExports;
export default cssExports;
