// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'advancedToggle': string;
  'sectionTitle': string;
  'specifications': string;
}
export const cssExports: CssExports;
export default cssExports;
