// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonContainer': string;
  'buttonContainerContent': string;
  'buttons': string;
  'deleteSelectedButton': string;
  'dropdownContainer': string;
  'footer': string;
  'helpText': string;
  'inputContainer': string;
  'organizeSelectedButton': string;
  'selectedAuthorLabel': string;
  'tagsButton': string;
  'tooltipWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
