// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alternateTitle': string;
  'poster': string;
  'result': string;
  'subtitle': string;
  'tagContainer': string;
  'title': string;
  'titleText': string;
  'titleUnmonitored': string;
  'titles': string;
}
export const cssExports: CssExports;
export default cssExports;
