// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chip': string;
  'chipPaused': string;
  'container': string;
  'countIcon': string;
  'countItem': string;
  'countLabel': string;
  'countValue': string;
  'counts': string;
  'pauseButton': string;
  'statusIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
