// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backdrop': string;
  'currentItem': string;
  'currentItemLabel': string;
  'currentItemValue': string;
  'drawer': string;
  'headerRow': string;
  'headerText': string;
  'row': string;
  'rowCounts': string;
  'rowLabel': string;
  'section': string;
  'sectionTitle': string;
  'subtitle': string;
  'summaryCard': string;
  'summaryGrid': string;
  'summaryLabel': string;
  'summaryValue': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
