// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alertContent': string;
  'inlineFormGroup': string;
  'label': string;
  'locationInfo': string;
  'logLevelContainer': string;
  'logLevelDropdown': string;
  'logLevelWarning': string;
}
export const cssExports: CssExports;
export default cssExports;
