// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'proxyModeContent': string;
  'radioDescription': string;
  'radioGroup': string;
  'radioInput': string;
  'radioLabel': string;
  'radioOption': string;
  'radioText': string;
}
export const cssExports: CssExports;
export default cssExports;
