// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absMappingArrow': string;
  'absMappingBadge': string;
  'absMappingDestination': string;
  'absMappingGridHeader': string;
  'absMappingHelp': string;
  'absMappingPath': string;
  'absMappingRow': string;
  'absMappingSource': string;
  'absMappingTitle': string;
  'absMappingToolbar': string;
  'absMappings': string;
  'deleteButton': string;
  'message': string;
}
export const cssExports: CssExports;
export default cssExports;
