// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'header': string;
  'infoIcon': string;
  'infoText': string;
  'inlineForm': string;
}
export const cssExports: CssExports;
export default cssExports;
