// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'conversionSettingsLink': string;
  'customFormatsSection': string;
  'deleteButtonContainer': string;
  'deleteButtonWithReason': string;
  'deleteDisabledReasonIcon': string;
  'formGroupWrapper': string;
  'formGroupsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
