// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'metadataStatusAlert': string;
  'metadataStatusContainer': string;
  'metadataStatusHeader': string;
  'metadataStatusLine': string;
  'metadataStatusLines': string;
  'metadataStatusTitle': string;
  'resettingNote': string;
}
export const cssExports: CssExports;
export default cssExports;
