// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addMetadataProfile': string;
  'addText': string;
  'center': string;
  'columnHeader': string;
  'metadataProfiles': string;
  'profileColumn': string;
  'profilesColumns': string;
}
export const cssExports: CssExports;
export default cssExports;
