// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBadge': string;
  'addFormat': string;
  'badge': string;
  'existingFormat': string;
  'formatActions': string;
  'instanceLink': string;
  'instanceList': string;
  'unavailableFormat': string;
}
export const cssExports: CssExports;
export default cssExports;
