// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'moreIndicator': string;
  'narratorComposite': string;
  'narratorDisplay': string;
  'narratorText': string;
  'narratorTextPlain': string;
  'searchIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
