// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'container': string;
  'content': string;
  'controls': string;
  'editorSelect': string;
  'ended': string;
  'link': string;
  'mediaProfile': string;
  'mediaProfileIcon': string;
  'mediaSummary': string;
  'monitoringIconEnd': string;
  'monitoringIconStart': string;
  'monitoringLabel': string;
  'monitoringSummary': string;
  'nextAiring': string;
  'overlayTitle': string;
  'poster': string;
  'posterContainer': string;
  'profileName': string;
  'selectable': string;
  'selected': string;
  'title': string;
  'unselected': string;
}
export const cssExports: CssExports;
export default cssExports;
