// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'deleteButton': string;
  'mappingArrow': string;
  'mappingGridHeader': string;
  'mappingHelp': string;
  'mappingRow': string;
  'mappingSection': string;
  'mappingSide': string;
  'mappingTitle': string;
  'pathSuggestion': string;
  'pathSuggestions': string;
}
export const cssExports: CssExports;
export default cssExports;
