// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteButton': string;
  'linkToggleButton': string;
  'linkToggleMiddleButton': string;
  'linkedPairConnector': string;
  'linkedPairContainer': string;
  'linkedPairFields': string;
  'linkedPairHelpText': string;
  'linkedPairLine': string;
  'linkedPairToggle': string;
  'message': string;
}
export const cssExports: CssExports;
export default cssExports;
