// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'author': string;
  'bookTitle': string;
  'mediaType': string;
  'narrator': string;
}
export const cssExports: CssExports;
export default cssExports;
