// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'changelogSection': string;
  'descriptionList': string;
  'roadmapSection': string;
}
export const cssExports: CssExports;
export default cssExports;
