// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actions': string;
  'freeSpace': string;
  'metadataProfileCell': string;
  'missingProfile': string;
  'name': string;
  'nameCell': string;
  'notConfigured': string;
  'path': string;
  'pathCell': string;
  'profileRow': string;
  'profileType': string;
  'profileValue': string;
  'qualityProfileCell': string;
  'typeCell': string;
  'typeLabels': string;
}
export const cssExports: CssExports;
export default cssExports;
