// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsHeader': string;
  'addRootFolderContainer': string;
  'addRootFolderIcon': string;
  'freeSpaceHeader': string;
  'metadataProfileHeader': string;
  'nameHeader': string;
  'pathHeader': string;
  'qualityProfileHeader': string;
  'typeHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
