// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'duration': string;
  'number': string;
  'time': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
