// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authorIcon': string;
  'authorName': string;
  'counterBox': string;
  'counterContent': string;
  'counterGrid': string;
  'counterLabel': string;
  'counterValue': string;
  'flyIn': string;
  'importProgressContainer': string;
  'matchedBook': string;
  'matchedIcon': string;
  'matchedLabel': string;
  'matchedTitle': string;
  'miniProgressBar': string;
  'miniProgressFill': string;
  'pauseButton': string;
  'pauseButtonPaused': string;
  'processingAuthor': string;
  'processingAuthorPaused': string;
  'processingLabel': string;
  'progressBarSection': string;
  'slideIn': string;
}
export const cssExports: CssExports;
export default cssExports;
