// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionContainer': string;
  'actionIcon': string;
  'actionText': string;
  'clickable': string;
  'content': string;
  'error': string;
  'hovered': string;
  'iconContainer': string;
  'importProgress': string;
  'info': string;
  'message': string;
  'paused': string;
  'pulse': string;
  'scanProgress': string;
  'success': string;
  'text': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
