// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bookInfo': string;
  'discoveryStats': string;
  'modalFooter': string;
  'narratorDescription': string;
  'narratorSection': string;
  'searchForNewBookContainer': string;
  'searchForNewBookInput': string;
  'searchForNewBookLabel': string;
  'searchForNewBookLabelContainer': string;
  'searchInfo': string;
  'stat': string;
  'statLabel': string;
  'statValue': string;
}
export const cssExports: CssExports;
export default cssExports;
