// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'bookCover': string;
  'duration': string;
  'editionTitle': string;
  'inLibraryStatus': string;
  'monitoredStatus': string;
  'narrator': string;
  'narratorContainer': string;
  'narratorDetails': string;
  'narratorName': string;
  'overview': string;
  'publisherDivider': string;
  'publisherRow': string;
  'rating': string;
  'releaseYear': string;
  'statusIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
