// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'categoryCheck': string;
  'categoryDescription': string;
  'categoryGrid': string;
  'categoryInput': string;
  'categoryName': string;
  'categoryOption': string;
  'categoryPicker': string;
  'categoryPickerActions': string;
  'categoryPickerCount': string;
  'categoryPickerHeader': string;
  'categoryPickerTitle': string;
  'categoryText': string;
  'intro': string;
  'restoreWarnings': string;
  'statusAlert': string;
}
export const cssExports: CssExports;
export default cssExports;
