// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonContent': string;
  'buttonIcon': string;
  'buttonSubtext': string;
  'buttonText': string;
  'donationButton': string;
  'donationButtons': string;
  'donationContainer': string;
  'donationFooter': string;
  'donationText': string;
  'logo': string;
  'logoContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
